// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Tamos.MetaCoding.GeneratorDesign.GrpcBuild
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using Tamos.AbleOrigin.Common;
    using Tamos.MetaCoding.GeneratorDesign;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "E:\Projects\Private\Tamos.Origin\Tamos.MetaCoding\Tamos.MetaCoding.GeneratorDesign\GrpcBuild\TmplServiceImplement.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class TmplServiceImplement : TmplServiceImplementBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("/*------------------------------------------\r\n* <auto-generated>\r\n* 自动生成文件，请不要直接编" +
                    "辑！\r\n* </auto-generated>\r\n------------------------------------------*/\r\nusing Sys" +
                    "tem;\r\nusing System.Collections.Generic;\r\nusing System.Threading.Tasks;\r\nusing ");
            
            #line 18 "E:\Projects\Private\Tamos.Origin\Tamos.MetaCoding\Tamos.MetaCoding.GeneratorDesign\GrpcBuild\TmplServiceImplement.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GrpcBuildConfig.InfraNamespace));
            
            #line default
            #line hidden
            this.Write(".IOC;\r\nusing ");
            
            #line 19 "E:\Projects\Private\Tamos.Origin\Tamos.MetaCoding\Tamos.MetaCoding.GeneratorDesign\GrpcBuild\TmplServiceImplement.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GrpcBuildConfig.InfraNamespace));
            
            #line default
            #line hidden
            this.Write(".Booster;\r\nusing ");
            
            #line 20 "E:\Projects\Private\Tamos.Origin\Tamos.MetaCoding\Tamos.MetaCoding.GeneratorDesign\GrpcBuild\TmplServiceImplement.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GrpcBuildConfig.InfraNamespace));
            
            #line default
            #line hidden
            this.Write(".Log;\r\nusing ");
            
            #line 21 "E:\Projects\Private\Tamos.Origin\Tamos.MetaCoding\Tamos.MetaCoding.GeneratorDesign\GrpcBuild\TmplServiceImplement.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GrpcBuildConfig.InfraNamespace));
            
            #line default
            #line hidden
            this.Write(".DataProto;\r\n\r\n#if !PRECODEGEN\r\nnamespace ");
            
            #line 24 "E:\Projects\Private\Tamos.Origin\Tamos.MetaCoding\Tamos.MetaCoding.GeneratorDesign\GrpcBuild\TmplServiceImplement.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(config.OutNamespace.NoNull()));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n");
            
            #line 26 "E:\Projects\Private\Tamos.Origin\Tamos.MetaCoding\Tamos.MetaCoding.GeneratorDesign\GrpcBuild\TmplServiceImplement.tt"
 foreach (var dotNetType in file.TypeList) { 
            
            #line default
            #line hidden
            this.Write("    public partial class ");
            
            #line 27 "E:\Projects\Private\Tamos.Origin\Tamos.MetaCoding\Tamos.MetaCoding.GeneratorDesign\GrpcBuild\TmplServiceImplement.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(config.ServiceImplName));
            
            #line default
            #line hidden
            this.Write(" : ");
            
            #line 27 "E:\Projects\Private\Tamos.Origin\Tamos.MetaCoding\Tamos.MetaCoding.GeneratorDesign\GrpcBuild\TmplServiceImplement.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(config.ContractName));
            
            #line default
            #line hidden
            this.Write("\r\n    {\r\n");
            
            #line 29 "E:\Projects\Private\Tamos.Origin\Tamos.MetaCoding\Tamos.MetaCoding.GeneratorDesign\GrpcBuild\TmplServiceImplement.tt"
foreach (GrpcOperation oper in dotNetType.TypeMembers) {
            
            #line default
            #line hidden
            this.Write("        public ");
            
            #line 30 "E:\Projects\Private\Tamos.Origin\Tamos.MetaCoding\Tamos.MetaCoding.GeneratorDesign\GrpcBuild\TmplServiceImplement.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(config.OutSyncMethod ? oper.ProxyResTypeName : $"ValueTask<{oper.ProxyResTypeName}>"));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 30 "E:\Projects\Private\Tamos.Origin\Tamos.MetaCoding\Tamos.MetaCoding.GeneratorDesign\GrpcBuild\TmplServiceImplement.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture($" {oper.Name}({oper.ProxyReqTypeName} {GrpcOperation.Var_Para})"));
            
            #line default
            #line hidden
            this.Write("\r\n        {\r\n            ");
            
            #line 32 "E:\Projects\Private\Tamos.Origin\Tamos.MetaCoding\Tamos.MetaCoding.GeneratorDesign\GrpcBuild\TmplServiceImplement.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(oper.ResRawType ? $"{oper.ProxyResTypeName} _res_;" : $"var _res_ = new {oper.ProxyResTypeName}();"));
            
            #line default
            #line hidden
            this.Write("\r\n            try\r\n            {\r\n                ");
            
            #line 35 "E:\Projects\Private\Tamos.Origin\Tamos.MetaCoding\Tamos.MetaCoding.GeneratorDesign\GrpcBuild\TmplServiceImplement.tt"
 if (!oper.IsVoidReturn) this.Write(oper.ResRawType ? "_res_ = " : "_res_.P1 = "); 
                this.WriteLine($"ServiceLocator.GetInstance<{oper.RawInterface}>().{oper.MethodInfo.Name}({oper.GetRawCallParas()});");
                if (oper.ResCase == ParaCaseType.WrapOut) {
                var tag = 1;
                foreach (var outp in oper.FormOfParas(true)) {
            
            #line default
            #line hidden
            this.Write("                _res_.P");
            
            #line 40 "E:\Projects\Private\Tamos.Origin\Tamos.MetaCoding\Tamos.MetaCoding.GeneratorDesign\GrpcBuild\TmplServiceImplement.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(++tag));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 40 "E:\Projects\Private\Tamos.Origin\Tamos.MetaCoding\Tamos.MetaCoding.GeneratorDesign\GrpcBuild\TmplServiceImplement.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(outp.Name));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 41 "E:\Projects\Private\Tamos.Origin\Tamos.MetaCoding\Tamos.MetaCoding.GeneratorDesign\GrpcBuild\TmplServiceImplement.tt"
              }}
            
            #line default
            #line hidden
            this.Write("            }\r\n            catch (Exception e)\r\n            {\r\n                Lo" +
                    "gService.Error(e);\r\n                ");
            
            #line 46 "E:\Projects\Private\Tamos.Origin\Tamos.MetaCoding\Tamos.MetaCoding.GeneratorDesign\GrpcBuild\TmplServiceImplement.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(oper.ResRawType ? $"_res_ = new {oper.ProxyResTypeName}().Error(e.Message);" : "_res_.ErrorMsg = e.Message;"));
            
            #line default
            #line hidden
            this.Write("\r\n            }\r\n            return ");
            
            #line 48 "E:\Projects\Private\Tamos.Origin\Tamos.MetaCoding\Tamos.MetaCoding.GeneratorDesign\GrpcBuild\TmplServiceImplement.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(config.OutSyncMethod ? "_res_" : $"new ValueTask<{oper.ProxyResTypeName}>(_res_)"));
            
            #line default
            #line hidden
            this.Write(";\r\n        }\r\n\r\n");
            
            #line 51 "E:\Projects\Private\Tamos.Origin\Tamos.MetaCoding\Tamos.MetaCoding.GeneratorDesign\GrpcBuild\TmplServiceImplement.tt"
} //------- Operations End -------
            
            #line default
            #line hidden
            this.Write("    }\r\n\r\n");
            
            #line 54 "E:\Projects\Private\Tamos.Origin\Tamos.MetaCoding\Tamos.MetaCoding.GeneratorDesign\GrpcBuild\TmplServiceImplement.tt"
} //-------- TypeList End --------
            
            #line default
            #line hidden
            this.Write("}\r\n#endif");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 1 "E:\Projects\Private\Tamos.Origin\Tamos.MetaCoding\Tamos.MetaCoding.GeneratorDesign\GrpcBuild\TmplServiceImplement.tt"

private global::Tamos.MetaCoding.GeneratorDesign.GrpcBuildConfig _configField;

/// <summary>
/// Access the config parameter of the template.
/// </summary>
private global::Tamos.MetaCoding.GeneratorDesign.GrpcBuildConfig config
{
    get
    {
        return this._configField;
    }
}

private global::Tamos.MetaCoding.GeneratorDesign.CodeFile _fileField;

/// <summary>
/// Access the file parameter of the template.
/// </summary>
private global::Tamos.MetaCoding.GeneratorDesign.CodeFile file
{
    get
    {
        return this._fileField;
    }
}


/// <summary>
/// Initialize the template
/// </summary>
public virtual void Initialize()
{
    if ((this.Errors.HasErrors == false))
    {
bool configValueAcquired = false;
if (this.Session.ContainsKey("config"))
{
    this._configField = ((global::Tamos.MetaCoding.GeneratorDesign.GrpcBuildConfig)(this.Session["config"]));
    configValueAcquired = true;
}
if ((configValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("config");
    if ((data != null))
    {
        this._configField = ((global::Tamos.MetaCoding.GeneratorDesign.GrpcBuildConfig)(data));
    }
}
bool fileValueAcquired = false;
if (this.Session.ContainsKey("file"))
{
    this._fileField = ((global::Tamos.MetaCoding.GeneratorDesign.CodeFile)(this.Session["file"]));
    fileValueAcquired = true;
}
if ((fileValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("file");
    if ((data != null))
    {
        this._fileField = ((global::Tamos.MetaCoding.GeneratorDesign.CodeFile)(data));
    }
}


    }
}


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public class TmplServiceImplementBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
